apiVersion: v1
kind: Service
metadata:
  labels:
    app: ps-landing-ui
  name: ps-landing-ui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ps-landing-ui
